# Generated by Django 5.1 on 2024-08-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_alter_profile_institution_alter_profile_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="display",
            field=models.SmallIntegerField(
                choices=[(1, "Light mode"), (2, "Dark mode")], default=1
            ),
        ),
    ]
